substitutions:
  name: "Studio Filter"

esphome:
  name: "air-filter-studio"
  on_boot:
    - pulse_counter.set_total_pulses:
        id: filter_counter
        value: !lambda "return id(filter_age) * 100;"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  platform: esphome

logger:
  logs:
    pulse_counter: none
    number: none
    sensor: none
    switch: none

preferences:
  flash_write_interval: 180s

globals:
  - id: filter_age
    type: int
    restore_value: yes

binary_sensor:
  - platform: template
    name: $name Dirty
    id: filter_dirty
    icon: mdi:trash-can-outline
    trigger_on_initial_state: true

button:
  - platform: template
    name: $name Reset
    id: reset_button
    icon: mdi:redo
    on_press:
      - pulse_counter.set_total_pulses:
          id: filter_counter
          value: 0
      - delay: 1s
      - switch.turn_off: onboard_led
      - lambda: |-
          id(filter_dirty).publish_state(false);
      - lambda: |-
          global_preferences->sync();

number:
  - platform: template
    name: "${name} Speed"
    id: fan_speed
    icon: mdi:air-filter
    update_interval: never
    optimistic: true
    min_value: 0
    max_value: 6
    initial_value: 0
    step: 1
    set_action:
      - if:
          condition:
            - lambda: 'return x >= 1;'
          then:
            - switch.turn_on: fan_mosfet
            - servo.write:
                id: fan_motor
                level: 1
            - output.set_level:
                id: fan_pwm
                level: !lambda 'return ((float)x) / 6.0;'
          else:
            - switch.turn_off: fan_mosfet
            - output.set_level:
                id: fan_pwm
                level: 0.0

sensor:
  - platform: pulse_counter
    pin: GPIO4
    id: filter_counter
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 2s
    filters:
      - multiply: 0.0001
    total:
      name: $name Age
      icon: mdi:biohazard
      unit_of_measurement: Age
      filters:
        - multiply: 0.01
      on_value:
        - lambda: |-
            id(filter_age) = x;
        - lambda: |-
            int timer = 3153600;  // 6 months in seconds
            if (x >= timer) {
              id(onboard_led).publish_state(true);
              id(filter_dirty).publish_state(true);
            }

  - platform: template
    name: "${name} Time Until Replacement"
    unit_of_measurement: "days"
    icon: mdi:calendar-clock
    lambda: |-
      float remaining = 3153600 - id(filter_age);
      if (remaining < 0) remaining = 0;
      return remaining / 86400;  // seconds to days
    update_interval: 60s

servo:
  - id: fan_motor
    output: fan_pwm
    max_level: 50%

output:
  - platform: ledc
    id: fan_pwm
    pin: GPIO5
    frequency: 100
    channel: 0

switch:
  - platform: gpio
    pin: GPIO10
    id: fan_mosfet
    on_turn_on:
      - switch.turn_on: onboard_led
    on_turn_off:
      - switch.turn_off: onboard_led

  - platform: gpio
    id: onboard_led
    pin:
      number: GPIO3
      inverted: true
